[workspace]
members = [
    "crates/engine",
    "crates/dungeon-crawler",
    "crates/ui"
]
resolver = "2"

[profile.release]
lto = "thin"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3