[workspace]
members = [
    "crates/dungeon-crawler-android"
]
default-members = [
    "crates/engine",
    "crates/dungeon-crawler",
    "crates/map",
    "crates/ui"
]

resolver = "2"

[profile.release]
lto = "thin"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3