[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
taffy = { git = "https://github.com/DioxusLabs/taffy" }

[profile.release]
incremental = true
